name: ter
recipe: symfony
config:
  php: '8.1'
  webroot: /public
  cache: redis
  database: mysql:5.7.24
  composer_version: '2.2.12'
services:
  node:
    type: node:14
    command: npm start
tooling:
  node:
    service: node
  npm:
    service: node
  yarn: 
    service: node